/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import { Context as ContextModule } from "./api/types/context"


declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  AssetCreateNestedManyWithoutPortfolioInput: { // input type
    connect?: NexusGenInputs['AssetWhereUniqueInput'][] | null; // [AssetWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['AssetCreateOrConnectWithoutPortfolioInput'][] | null; // [AssetCreateOrConnectWithoutPortfolioInput!]
    create?: NexusGenInputs['AssetCreateWithoutPortfolioInput'][] | null; // [AssetCreateWithoutPortfolioInput!]
  }
  AssetCreateNestedOneWithoutPrivateAssetInput: { // input type
    connect?: NexusGenInputs['AssetWhereUniqueInput'] | null; // AssetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['AssetCreateOrConnectWithoutPrivateAssetInput'] | null; // AssetCreateOrConnectWithoutPrivateAssetInput
    create?: NexusGenInputs['AssetCreateWithoutPrivateAssetInput'] | null; // AssetCreateWithoutPrivateAssetInput
  }
  AssetCreateNestedOneWithoutPublicAssetInput: { // input type
    connect?: NexusGenInputs['AssetWhereUniqueInput'] | null; // AssetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['AssetCreateOrConnectWithoutPublicAssetInput'] | null; // AssetCreateOrConnectWithoutPublicAssetInput
    create?: NexusGenInputs['AssetCreateWithoutPublicAssetInput'] | null; // AssetCreateWithoutPublicAssetInput
  }
  AssetCreateOrConnectWithoutPortfolioInput: { // input type
    create: NexusGenInputs['AssetCreateWithoutPortfolioInput']; // AssetCreateWithoutPortfolioInput!
    where: NexusGenInputs['AssetWhereUniqueInput']; // AssetWhereUniqueInput!
  }
  AssetCreateOrConnectWithoutPrivateAssetInput: { // input type
    create: NexusGenInputs['AssetCreateWithoutPrivateAssetInput']; // AssetCreateWithoutPrivateAssetInput!
    where: NexusGenInputs['AssetWhereUniqueInput']; // AssetWhereUniqueInput!
  }
  AssetCreateOrConnectWithoutPublicAssetInput: { // input type
    create: NexusGenInputs['AssetCreateWithoutPublicAssetInput']; // AssetCreateWithoutPublicAssetInput!
    where: NexusGenInputs['AssetWhereUniqueInput']; // AssetWhereUniqueInput!
  }
  AssetCreateWithoutPortfolioInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    name: string; // String!
    privateAsset?: NexusGenInputs['PrivateAssetCreateNestedOneWithoutBaseAssetInput'] | null; // PrivateAssetCreateNestedOneWithoutBaseAssetInput
    publicAsset?: NexusGenInputs['PublicAssetCreateNestedOneWithoutBaseAssetInput'] | null; // PublicAssetCreateNestedOneWithoutBaseAssetInput
    quantity?: number | null; // Int
    transactions?: NexusGenInputs['TransactionRecordCreateNestedManyWithoutAssetInput'] | null; // TransactionRecordCreateNestedManyWithoutAssetInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  AssetCreateWithoutPrivateAssetInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    name: string; // String!
    portfolio: NexusGenInputs['PortfolioCreateNestedOneWithoutAssetsInput']; // PortfolioCreateNestedOneWithoutAssetsInput!
    publicAsset?: NexusGenInputs['PublicAssetCreateNestedOneWithoutBaseAssetInput'] | null; // PublicAssetCreateNestedOneWithoutBaseAssetInput
    quantity?: number | null; // Int
    transactions?: NexusGenInputs['TransactionRecordCreateNestedManyWithoutAssetInput'] | null; // TransactionRecordCreateNestedManyWithoutAssetInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  AssetCreateWithoutPublicAssetInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    name: string; // String!
    portfolio: NexusGenInputs['PortfolioCreateNestedOneWithoutAssetsInput']; // PortfolioCreateNestedOneWithoutAssetsInput!
    privateAsset?: NexusGenInputs['PrivateAssetCreateNestedOneWithoutBaseAssetInput'] | null; // PrivateAssetCreateNestedOneWithoutBaseAssetInput
    quantity?: number | null; // Int
    transactions?: NexusGenInputs['TransactionRecordCreateNestedManyWithoutAssetInput'] | null; // TransactionRecordCreateNestedManyWithoutAssetInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  AssetScalarWhereInput: { // input type
    AND?: NexusGenInputs['AssetScalarWhereInput'][] | null; // [AssetScalarWhereInput!]
    NOT?: NexusGenInputs['AssetScalarWhereInput'][] | null; // [AssetScalarWhereInput!]
    OR?: NexusGenInputs['AssetScalarWhereInput'][] | null; // [AssetScalarWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    description?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    portfolioId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    quantity?: NexusGenInputs['IntFilter'] | null; // IntFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  AssetUpdateManyMutationInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    quantity?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  AssetUpdateManyWithWhereWithoutPortfolioInput: { // input type
    data: NexusGenInputs['AssetUpdateManyMutationInput']; // AssetUpdateManyMutationInput!
    where: NexusGenInputs['AssetScalarWhereInput']; // AssetScalarWhereInput!
  }
  AssetUpdateManyWithoutPortfolioInput: { // input type
    connect?: NexusGenInputs['AssetWhereUniqueInput'][] | null; // [AssetWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['AssetCreateOrConnectWithoutPortfolioInput'][] | null; // [AssetCreateOrConnectWithoutPortfolioInput!]
    create?: NexusGenInputs['AssetCreateWithoutPortfolioInput'][] | null; // [AssetCreateWithoutPortfolioInput!]
    delete?: NexusGenInputs['AssetWhereUniqueInput'][] | null; // [AssetWhereUniqueInput!]
    deleteMany?: NexusGenInputs['AssetScalarWhereInput'][] | null; // [AssetScalarWhereInput!]
    disconnect?: NexusGenInputs['AssetWhereUniqueInput'][] | null; // [AssetWhereUniqueInput!]
    set?: NexusGenInputs['AssetWhereUniqueInput'][] | null; // [AssetWhereUniqueInput!]
    update?: NexusGenInputs['AssetUpdateWithWhereUniqueWithoutPortfolioInput'][] | null; // [AssetUpdateWithWhereUniqueWithoutPortfolioInput!]
    updateMany?: NexusGenInputs['AssetUpdateManyWithWhereWithoutPortfolioInput'][] | null; // [AssetUpdateManyWithWhereWithoutPortfolioInput!]
    upsert?: NexusGenInputs['AssetUpsertWithWhereUniqueWithoutPortfolioInput'][] | null; // [AssetUpsertWithWhereUniqueWithoutPortfolioInput!]
  }
  AssetUpdateOneRequiredWithoutPrivateAssetInput: { // input type
    connect?: NexusGenInputs['AssetWhereUniqueInput'] | null; // AssetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['AssetCreateOrConnectWithoutPrivateAssetInput'] | null; // AssetCreateOrConnectWithoutPrivateAssetInput
    create?: NexusGenInputs['AssetCreateWithoutPrivateAssetInput'] | null; // AssetCreateWithoutPrivateAssetInput
    update?: NexusGenInputs['AssetUpdateWithoutPrivateAssetInput'] | null; // AssetUpdateWithoutPrivateAssetInput
    upsert?: NexusGenInputs['AssetUpsertWithoutPrivateAssetInput'] | null; // AssetUpsertWithoutPrivateAssetInput
  }
  AssetUpdateOneRequiredWithoutPublicAssetInput: { // input type
    connect?: NexusGenInputs['AssetWhereUniqueInput'] | null; // AssetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['AssetCreateOrConnectWithoutPublicAssetInput'] | null; // AssetCreateOrConnectWithoutPublicAssetInput
    create?: NexusGenInputs['AssetCreateWithoutPublicAssetInput'] | null; // AssetCreateWithoutPublicAssetInput
    update?: NexusGenInputs['AssetUpdateWithoutPublicAssetInput'] | null; // AssetUpdateWithoutPublicAssetInput
    upsert?: NexusGenInputs['AssetUpsertWithoutPublicAssetInput'] | null; // AssetUpsertWithoutPublicAssetInput
  }
  AssetUpdateWithWhereUniqueWithoutPortfolioInput: { // input type
    data: NexusGenInputs['AssetUpdateWithoutPortfolioInput']; // AssetUpdateWithoutPortfolioInput!
    where: NexusGenInputs['AssetWhereUniqueInput']; // AssetWhereUniqueInput!
  }
  AssetUpdateWithoutPortfolioInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    privateAsset?: NexusGenInputs['PrivateAssetUpdateOneWithoutBaseAssetInput'] | null; // PrivateAssetUpdateOneWithoutBaseAssetInput
    publicAsset?: NexusGenInputs['PublicAssetUpdateOneWithoutBaseAssetInput'] | null; // PublicAssetUpdateOneWithoutBaseAssetInput
    quantity?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    transactions?: NexusGenInputs['TransactionRecordUpdateManyWithoutAssetInput'] | null; // TransactionRecordUpdateManyWithoutAssetInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  AssetUpdateWithoutPrivateAssetInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    portfolio?: NexusGenInputs['PortfolioUpdateOneRequiredWithoutAssetsInput'] | null; // PortfolioUpdateOneRequiredWithoutAssetsInput
    publicAsset?: NexusGenInputs['PublicAssetUpdateOneWithoutBaseAssetInput'] | null; // PublicAssetUpdateOneWithoutBaseAssetInput
    quantity?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    transactions?: NexusGenInputs['TransactionRecordUpdateManyWithoutAssetInput'] | null; // TransactionRecordUpdateManyWithoutAssetInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  AssetUpdateWithoutPublicAssetInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    portfolio?: NexusGenInputs['PortfolioUpdateOneRequiredWithoutAssetsInput'] | null; // PortfolioUpdateOneRequiredWithoutAssetsInput
    privateAsset?: NexusGenInputs['PrivateAssetUpdateOneWithoutBaseAssetInput'] | null; // PrivateAssetUpdateOneWithoutBaseAssetInput
    quantity?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    transactions?: NexusGenInputs['TransactionRecordUpdateManyWithoutAssetInput'] | null; // TransactionRecordUpdateManyWithoutAssetInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  AssetUpsertWithWhereUniqueWithoutPortfolioInput: { // input type
    create: NexusGenInputs['AssetCreateWithoutPortfolioInput']; // AssetCreateWithoutPortfolioInput!
    update: NexusGenInputs['AssetUpdateWithoutPortfolioInput']; // AssetUpdateWithoutPortfolioInput!
    where: NexusGenInputs['AssetWhereUniqueInput']; // AssetWhereUniqueInput!
  }
  AssetUpsertWithoutPrivateAssetInput: { // input type
    create: NexusGenInputs['AssetCreateWithoutPrivateAssetInput']; // AssetCreateWithoutPrivateAssetInput!
    update: NexusGenInputs['AssetUpdateWithoutPrivateAssetInput']; // AssetUpdateWithoutPrivateAssetInput!
  }
  AssetUpsertWithoutPublicAssetInput: { // input type
    create: NexusGenInputs['AssetCreateWithoutPublicAssetInput']; // AssetCreateWithoutPublicAssetInput!
    update: NexusGenInputs['AssetUpdateWithoutPublicAssetInput']; // AssetUpdateWithoutPublicAssetInput!
  }
  AssetWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  DateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  EnumTransactionTypeFieldUpdateOperationsInput: { // input type
    set?: NexusGenEnums['TransactionType'] | null; // TransactionType
  }
  EnumTransactionTypeFilter: { // input type
    equals?: NexusGenEnums['TransactionType'] | null; // TransactionType
    in?: NexusGenEnums['TransactionType'][] | null; // [TransactionType!]
    not?: NexusGenInputs['NestedEnumTransactionTypeFilter'] | null; // NestedEnumTransactionTypeFilter
    notIn?: NexusGenEnums['TransactionType'][] | null; // [TransactionType!]
  }
  HistoricalValueCreateInput: { // input type
    asset: NexusGenInputs['PrivateAssetCreateNestedOneWithoutHistoricalValuesInput']; // PrivateAssetCreateNestedOneWithoutHistoricalValuesInput!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    currency: string; // String!
    date?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    unitPrice: number; // Int!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  HistoricalValueCreateNestedManyWithoutAssetInput: { // input type
    connect?: NexusGenInputs['HistoricalValueWhereUniqueInput'][] | null; // [HistoricalValueWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['HistoricalValueCreateOrConnectWithoutAssetInput'][] | null; // [HistoricalValueCreateOrConnectWithoutAssetInput!]
    create?: NexusGenInputs['HistoricalValueCreateWithoutAssetInput'][] | null; // [HistoricalValueCreateWithoutAssetInput!]
  }
  HistoricalValueCreateOrConnectWithoutAssetInput: { // input type
    create: NexusGenInputs['HistoricalValueCreateWithoutAssetInput']; // HistoricalValueCreateWithoutAssetInput!
    where: NexusGenInputs['HistoricalValueWhereUniqueInput']; // HistoricalValueWhereUniqueInput!
  }
  HistoricalValueCreateWithoutAssetInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    currency: string; // String!
    date?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    unitPrice: number; // Int!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  HistoricalValueScalarWhereInput: { // input type
    AND?: NexusGenInputs['HistoricalValueScalarWhereInput'][] | null; // [HistoricalValueScalarWhereInput!]
    NOT?: NexusGenInputs['HistoricalValueScalarWhereInput'][] | null; // [HistoricalValueScalarWhereInput!]
    OR?: NexusGenInputs['HistoricalValueScalarWhereInput'][] | null; // [HistoricalValueScalarWhereInput!]
    assetId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    currency?: NexusGenInputs['StringFilter'] | null; // StringFilter
    date?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    description?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    unitPrice?: NexusGenInputs['IntFilter'] | null; // IntFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  HistoricalValueUpdateInput: { // input type
    asset?: NexusGenInputs['PrivateAssetUpdateOneRequiredWithoutHistoricalValuesInput'] | null; // PrivateAssetUpdateOneRequiredWithoutHistoricalValuesInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    currency?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    date?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    unitPrice?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  HistoricalValueUpdateManyMutationInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    currency?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    date?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    unitPrice?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  HistoricalValueUpdateManyWithWhereWithoutAssetInput: { // input type
    data: NexusGenInputs['HistoricalValueUpdateManyMutationInput']; // HistoricalValueUpdateManyMutationInput!
    where: NexusGenInputs['HistoricalValueScalarWhereInput']; // HistoricalValueScalarWhereInput!
  }
  HistoricalValueUpdateManyWithoutAssetInput: { // input type
    connect?: NexusGenInputs['HistoricalValueWhereUniqueInput'][] | null; // [HistoricalValueWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['HistoricalValueCreateOrConnectWithoutAssetInput'][] | null; // [HistoricalValueCreateOrConnectWithoutAssetInput!]
    create?: NexusGenInputs['HistoricalValueCreateWithoutAssetInput'][] | null; // [HistoricalValueCreateWithoutAssetInput!]
    delete?: NexusGenInputs['HistoricalValueWhereUniqueInput'][] | null; // [HistoricalValueWhereUniqueInput!]
    deleteMany?: NexusGenInputs['HistoricalValueScalarWhereInput'][] | null; // [HistoricalValueScalarWhereInput!]
    disconnect?: NexusGenInputs['HistoricalValueWhereUniqueInput'][] | null; // [HistoricalValueWhereUniqueInput!]
    set?: NexusGenInputs['HistoricalValueWhereUniqueInput'][] | null; // [HistoricalValueWhereUniqueInput!]
    update?: NexusGenInputs['HistoricalValueUpdateWithWhereUniqueWithoutAssetInput'][] | null; // [HistoricalValueUpdateWithWhereUniqueWithoutAssetInput!]
    updateMany?: NexusGenInputs['HistoricalValueUpdateManyWithWhereWithoutAssetInput'][] | null; // [HistoricalValueUpdateManyWithWhereWithoutAssetInput!]
    upsert?: NexusGenInputs['HistoricalValueUpsertWithWhereUniqueWithoutAssetInput'][] | null; // [HistoricalValueUpsertWithWhereUniqueWithoutAssetInput!]
  }
  HistoricalValueUpdateWithWhereUniqueWithoutAssetInput: { // input type
    data: NexusGenInputs['HistoricalValueUpdateWithoutAssetInput']; // HistoricalValueUpdateWithoutAssetInput!
    where: NexusGenInputs['HistoricalValueWhereUniqueInput']; // HistoricalValueWhereUniqueInput!
  }
  HistoricalValueUpdateWithoutAssetInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    currency?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    date?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    unitPrice?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  HistoricalValueUpsertWithWhereUniqueWithoutAssetInput: { // input type
    create: NexusGenInputs['HistoricalValueCreateWithoutAssetInput']; // HistoricalValueCreateWithoutAssetInput!
    update: NexusGenInputs['HistoricalValueUpdateWithoutAssetInput']; // HistoricalValueUpdateWithoutAssetInput!
    where: NexusGenInputs['HistoricalValueWhereUniqueInput']; // HistoricalValueWhereUniqueInput!
  }
  HistoricalValueWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  IntFieldUpdateOperationsInput: { // input type
    decrement?: number | null; // Int
    divide?: number | null; // Int
    increment?: number | null; // Int
    multiply?: number | null; // Int
    set?: number | null; // Int
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedEnumTransactionTypeFilter: { // input type
    equals?: NexusGenEnums['TransactionType'] | null; // TransactionType
    in?: NexusGenEnums['TransactionType'][] | null; // [TransactionType!]
    not?: NexusGenInputs['NestedEnumTransactionTypeFilter'] | null; // NestedEnumTransactionTypeFilter
    notIn?: NexusGenEnums['TransactionType'][] | null; // [TransactionType!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NullableStringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  PortfolioCreateInput: { // input type
    assets?: NexusGenInputs['AssetCreateNestedManyWithoutPortfolioInput'] | null; // AssetCreateNestedManyWithoutPortfolioInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    name: string; // String!
    owner: NexusGenInputs['UserCreateNestedOneWithoutPortfoliosInput']; // UserCreateNestedOneWithoutPortfoliosInput!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PortfolioCreateNestedManyWithoutOwnerInput: { // input type
    connect?: NexusGenInputs['PortfolioWhereUniqueInput'][] | null; // [PortfolioWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PortfolioCreateOrConnectWithoutOwnerInput'][] | null; // [PortfolioCreateOrConnectWithoutOwnerInput!]
    create?: NexusGenInputs['PortfolioCreateWithoutOwnerInput'][] | null; // [PortfolioCreateWithoutOwnerInput!]
  }
  PortfolioCreateNestedOneWithoutAssetsInput: { // input type
    connect?: NexusGenInputs['PortfolioWhereUniqueInput'] | null; // PortfolioWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PortfolioCreateOrConnectWithoutAssetsInput'] | null; // PortfolioCreateOrConnectWithoutAssetsInput
    create?: NexusGenInputs['PortfolioCreateWithoutAssetsInput'] | null; // PortfolioCreateWithoutAssetsInput
  }
  PortfolioCreateOrConnectWithoutAssetsInput: { // input type
    create: NexusGenInputs['PortfolioCreateWithoutAssetsInput']; // PortfolioCreateWithoutAssetsInput!
    where: NexusGenInputs['PortfolioWhereUniqueInput']; // PortfolioWhereUniqueInput!
  }
  PortfolioCreateOrConnectWithoutOwnerInput: { // input type
    create: NexusGenInputs['PortfolioCreateWithoutOwnerInput']; // PortfolioCreateWithoutOwnerInput!
    where: NexusGenInputs['PortfolioWhereUniqueInput']; // PortfolioWhereUniqueInput!
  }
  PortfolioCreateWithoutAssetsInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    name: string; // String!
    owner: NexusGenInputs['UserCreateNestedOneWithoutPortfoliosInput']; // UserCreateNestedOneWithoutPortfoliosInput!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PortfolioCreateWithoutOwnerInput: { // input type
    assets?: NexusGenInputs['AssetCreateNestedManyWithoutPortfolioInput'] | null; // AssetCreateNestedManyWithoutPortfolioInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PortfolioScalarWhereInput: { // input type
    AND?: NexusGenInputs['PortfolioScalarWhereInput'][] | null; // [PortfolioScalarWhereInput!]
    NOT?: NexusGenInputs['PortfolioScalarWhereInput'][] | null; // [PortfolioScalarWhereInput!]
    OR?: NexusGenInputs['PortfolioScalarWhereInput'][] | null; // [PortfolioScalarWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    description?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    userId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  PortfolioUpdateInput: { // input type
    assets?: NexusGenInputs['AssetUpdateManyWithoutPortfolioInput'] | null; // AssetUpdateManyWithoutPortfolioInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    owner?: NexusGenInputs['UserUpdateOneRequiredWithoutPortfoliosInput'] | null; // UserUpdateOneRequiredWithoutPortfoliosInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PortfolioUpdateManyMutationInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PortfolioUpdateManyWithWhereWithoutOwnerInput: { // input type
    data: NexusGenInputs['PortfolioUpdateManyMutationInput']; // PortfolioUpdateManyMutationInput!
    where: NexusGenInputs['PortfolioScalarWhereInput']; // PortfolioScalarWhereInput!
  }
  PortfolioUpdateManyWithoutOwnerInput: { // input type
    connect?: NexusGenInputs['PortfolioWhereUniqueInput'][] | null; // [PortfolioWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PortfolioCreateOrConnectWithoutOwnerInput'][] | null; // [PortfolioCreateOrConnectWithoutOwnerInput!]
    create?: NexusGenInputs['PortfolioCreateWithoutOwnerInput'][] | null; // [PortfolioCreateWithoutOwnerInput!]
    delete?: NexusGenInputs['PortfolioWhereUniqueInput'][] | null; // [PortfolioWhereUniqueInput!]
    deleteMany?: NexusGenInputs['PortfolioScalarWhereInput'][] | null; // [PortfolioScalarWhereInput!]
    disconnect?: NexusGenInputs['PortfolioWhereUniqueInput'][] | null; // [PortfolioWhereUniqueInput!]
    set?: NexusGenInputs['PortfolioWhereUniqueInput'][] | null; // [PortfolioWhereUniqueInput!]
    update?: NexusGenInputs['PortfolioUpdateWithWhereUniqueWithoutOwnerInput'][] | null; // [PortfolioUpdateWithWhereUniqueWithoutOwnerInput!]
    updateMany?: NexusGenInputs['PortfolioUpdateManyWithWhereWithoutOwnerInput'][] | null; // [PortfolioUpdateManyWithWhereWithoutOwnerInput!]
    upsert?: NexusGenInputs['PortfolioUpsertWithWhereUniqueWithoutOwnerInput'][] | null; // [PortfolioUpsertWithWhereUniqueWithoutOwnerInput!]
  }
  PortfolioUpdateOneRequiredWithoutAssetsInput: { // input type
    connect?: NexusGenInputs['PortfolioWhereUniqueInput'] | null; // PortfolioWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PortfolioCreateOrConnectWithoutAssetsInput'] | null; // PortfolioCreateOrConnectWithoutAssetsInput
    create?: NexusGenInputs['PortfolioCreateWithoutAssetsInput'] | null; // PortfolioCreateWithoutAssetsInput
    update?: NexusGenInputs['PortfolioUpdateWithoutAssetsInput'] | null; // PortfolioUpdateWithoutAssetsInput
    upsert?: NexusGenInputs['PortfolioUpsertWithoutAssetsInput'] | null; // PortfolioUpsertWithoutAssetsInput
  }
  PortfolioUpdateWithWhereUniqueWithoutOwnerInput: { // input type
    data: NexusGenInputs['PortfolioUpdateWithoutOwnerInput']; // PortfolioUpdateWithoutOwnerInput!
    where: NexusGenInputs['PortfolioWhereUniqueInput']; // PortfolioWhereUniqueInput!
  }
  PortfolioUpdateWithoutAssetsInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    owner?: NexusGenInputs['UserUpdateOneRequiredWithoutPortfoliosInput'] | null; // UserUpdateOneRequiredWithoutPortfoliosInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PortfolioUpdateWithoutOwnerInput: { // input type
    assets?: NexusGenInputs['AssetUpdateManyWithoutPortfolioInput'] | null; // AssetUpdateManyWithoutPortfolioInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PortfolioUpsertWithWhereUniqueWithoutOwnerInput: { // input type
    create: NexusGenInputs['PortfolioCreateWithoutOwnerInput']; // PortfolioCreateWithoutOwnerInput!
    update: NexusGenInputs['PortfolioUpdateWithoutOwnerInput']; // PortfolioUpdateWithoutOwnerInput!
    where: NexusGenInputs['PortfolioWhereUniqueInput']; // PortfolioWhereUniqueInput!
  }
  PortfolioUpsertWithoutAssetsInput: { // input type
    create: NexusGenInputs['PortfolioCreateWithoutAssetsInput']; // PortfolioCreateWithoutAssetsInput!
    update: NexusGenInputs['PortfolioUpdateWithoutAssetsInput']; // PortfolioUpdateWithoutAssetsInput!
  }
  PortfolioWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  PrivateAssetCreateInput: { // input type
    baseAsset: NexusGenInputs['AssetCreateNestedOneWithoutPrivateAssetInput']; // AssetCreateNestedOneWithoutPrivateAssetInput!
    historicalValues?: NexusGenInputs['HistoricalValueCreateNestedManyWithoutAssetInput'] | null; // HistoricalValueCreateNestedManyWithoutAssetInput
  }
  PrivateAssetCreateNestedOneWithoutBaseAssetInput: { // input type
    connect?: NexusGenInputs['PrivateAssetWhereUniqueInput'] | null; // PrivateAssetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PrivateAssetCreateOrConnectWithoutBaseAssetInput'] | null; // PrivateAssetCreateOrConnectWithoutBaseAssetInput
    create?: NexusGenInputs['PrivateAssetCreateWithoutBaseAssetInput'] | null; // PrivateAssetCreateWithoutBaseAssetInput
  }
  PrivateAssetCreateNestedOneWithoutHistoricalValuesInput: { // input type
    connect?: NexusGenInputs['PrivateAssetWhereUniqueInput'] | null; // PrivateAssetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PrivateAssetCreateOrConnectWithoutHistoricalValuesInput'] | null; // PrivateAssetCreateOrConnectWithoutHistoricalValuesInput
    create?: NexusGenInputs['PrivateAssetCreateWithoutHistoricalValuesInput'] | null; // PrivateAssetCreateWithoutHistoricalValuesInput
  }
  PrivateAssetCreateOrConnectWithoutBaseAssetInput: { // input type
    create: NexusGenInputs['PrivateAssetCreateWithoutBaseAssetInput']; // PrivateAssetCreateWithoutBaseAssetInput!
    where: NexusGenInputs['PrivateAssetWhereUniqueInput']; // PrivateAssetWhereUniqueInput!
  }
  PrivateAssetCreateOrConnectWithoutHistoricalValuesInput: { // input type
    create: NexusGenInputs['PrivateAssetCreateWithoutHistoricalValuesInput']; // PrivateAssetCreateWithoutHistoricalValuesInput!
    where: NexusGenInputs['PrivateAssetWhereUniqueInput']; // PrivateAssetWhereUniqueInput!
  }
  PrivateAssetCreateWithoutBaseAssetInput: { // input type
    historicalValues?: NexusGenInputs['HistoricalValueCreateNestedManyWithoutAssetInput'] | null; // HistoricalValueCreateNestedManyWithoutAssetInput
  }
  PrivateAssetCreateWithoutHistoricalValuesInput: { // input type
    baseAsset: NexusGenInputs['AssetCreateNestedOneWithoutPrivateAssetInput']; // AssetCreateNestedOneWithoutPrivateAssetInput!
  }
  PrivateAssetUpdateInput: { // input type
    baseAsset?: NexusGenInputs['AssetUpdateOneRequiredWithoutPrivateAssetInput'] | null; // AssetUpdateOneRequiredWithoutPrivateAssetInput
    historicalValues?: NexusGenInputs['HistoricalValueUpdateManyWithoutAssetInput'] | null; // HistoricalValueUpdateManyWithoutAssetInput
  }
  PrivateAssetUpdateOneRequiredWithoutHistoricalValuesInput: { // input type
    connect?: NexusGenInputs['PrivateAssetWhereUniqueInput'] | null; // PrivateAssetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PrivateAssetCreateOrConnectWithoutHistoricalValuesInput'] | null; // PrivateAssetCreateOrConnectWithoutHistoricalValuesInput
    create?: NexusGenInputs['PrivateAssetCreateWithoutHistoricalValuesInput'] | null; // PrivateAssetCreateWithoutHistoricalValuesInput
    update?: NexusGenInputs['PrivateAssetUpdateWithoutHistoricalValuesInput'] | null; // PrivateAssetUpdateWithoutHistoricalValuesInput
    upsert?: NexusGenInputs['PrivateAssetUpsertWithoutHistoricalValuesInput'] | null; // PrivateAssetUpsertWithoutHistoricalValuesInput
  }
  PrivateAssetUpdateOneWithoutBaseAssetInput: { // input type
    connect?: NexusGenInputs['PrivateAssetWhereUniqueInput'] | null; // PrivateAssetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PrivateAssetCreateOrConnectWithoutBaseAssetInput'] | null; // PrivateAssetCreateOrConnectWithoutBaseAssetInput
    create?: NexusGenInputs['PrivateAssetCreateWithoutBaseAssetInput'] | null; // PrivateAssetCreateWithoutBaseAssetInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['PrivateAssetUpdateWithoutBaseAssetInput'] | null; // PrivateAssetUpdateWithoutBaseAssetInput
    upsert?: NexusGenInputs['PrivateAssetUpsertWithoutBaseAssetInput'] | null; // PrivateAssetUpsertWithoutBaseAssetInput
  }
  PrivateAssetUpdateWithoutBaseAssetInput: { // input type
    historicalValues?: NexusGenInputs['HistoricalValueUpdateManyWithoutAssetInput'] | null; // HistoricalValueUpdateManyWithoutAssetInput
  }
  PrivateAssetUpdateWithoutHistoricalValuesInput: { // input type
    baseAsset?: NexusGenInputs['AssetUpdateOneRequiredWithoutPrivateAssetInput'] | null; // AssetUpdateOneRequiredWithoutPrivateAssetInput
  }
  PrivateAssetUpsertWithoutBaseAssetInput: { // input type
    create: NexusGenInputs['PrivateAssetCreateWithoutBaseAssetInput']; // PrivateAssetCreateWithoutBaseAssetInput!
    update: NexusGenInputs['PrivateAssetUpdateWithoutBaseAssetInput']; // PrivateAssetUpdateWithoutBaseAssetInput!
  }
  PrivateAssetUpsertWithoutHistoricalValuesInput: { // input type
    create: NexusGenInputs['PrivateAssetCreateWithoutHistoricalValuesInput']; // PrivateAssetCreateWithoutHistoricalValuesInput!
    update: NexusGenInputs['PrivateAssetUpdateWithoutHistoricalValuesInput']; // PrivateAssetUpdateWithoutHistoricalValuesInput!
  }
  PrivateAssetWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  PublicAssetCreateInput: { // input type
    baseAsset: NexusGenInputs['AssetCreateNestedOneWithoutPublicAssetInput']; // AssetCreateNestedOneWithoutPublicAssetInput!
    market?: string | null; // String
    symbol?: string | null; // String
  }
  PublicAssetCreateNestedOneWithoutBaseAssetInput: { // input type
    connect?: NexusGenInputs['PublicAssetWhereUniqueInput'] | null; // PublicAssetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PublicAssetCreateOrConnectWithoutBaseAssetInput'] | null; // PublicAssetCreateOrConnectWithoutBaseAssetInput
    create?: NexusGenInputs['PublicAssetCreateWithoutBaseAssetInput'] | null; // PublicAssetCreateWithoutBaseAssetInput
  }
  PublicAssetCreateOrConnectWithoutBaseAssetInput: { // input type
    create: NexusGenInputs['PublicAssetCreateWithoutBaseAssetInput']; // PublicAssetCreateWithoutBaseAssetInput!
    where: NexusGenInputs['PublicAssetWhereUniqueInput']; // PublicAssetWhereUniqueInput!
  }
  PublicAssetCreateWithoutBaseAssetInput: { // input type
    market?: string | null; // String
    symbol?: string | null; // String
  }
  PublicAssetUpdateInput: { // input type
    baseAsset?: NexusGenInputs['AssetUpdateOneRequiredWithoutPublicAssetInput'] | null; // AssetUpdateOneRequiredWithoutPublicAssetInput
    market?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    symbol?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  PublicAssetUpdateOneWithoutBaseAssetInput: { // input type
    connect?: NexusGenInputs['PublicAssetWhereUniqueInput'] | null; // PublicAssetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PublicAssetCreateOrConnectWithoutBaseAssetInput'] | null; // PublicAssetCreateOrConnectWithoutBaseAssetInput
    create?: NexusGenInputs['PublicAssetCreateWithoutBaseAssetInput'] | null; // PublicAssetCreateWithoutBaseAssetInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['PublicAssetUpdateWithoutBaseAssetInput'] | null; // PublicAssetUpdateWithoutBaseAssetInput
    upsert?: NexusGenInputs['PublicAssetUpsertWithoutBaseAssetInput'] | null; // PublicAssetUpsertWithoutBaseAssetInput
  }
  PublicAssetUpdateWithoutBaseAssetInput: { // input type
    market?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    symbol?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  PublicAssetUpsertWithoutBaseAssetInput: { // input type
    create: NexusGenInputs['PublicAssetCreateWithoutBaseAssetInput']; // PublicAssetCreateWithoutBaseAssetInput!
    update: NexusGenInputs['PublicAssetUpdateWithoutBaseAssetInput']; // PublicAssetUpdateWithoutBaseAssetInput!
  }
  PublicAssetWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  TransactionCreateInput: { // input type
    assetId: number; // Int!
    assetQuantity: number; // Int!
    currency: string; // String!
    note?: string | null; // String
    transactionType: NexusGenEnums['TransactionType']; // TransactionType!
    unitPrice: number; // Int!
  }
  TransactionRecordCreateNestedManyWithoutAssetInput: { // input type
    connect?: NexusGenInputs['TransactionRecordWhereUniqueInput'][] | null; // [TransactionRecordWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['TransactionRecordCreateOrConnectWithoutAssetInput'][] | null; // [TransactionRecordCreateOrConnectWithoutAssetInput!]
    create?: NexusGenInputs['TransactionRecordCreateWithoutAssetInput'][] | null; // [TransactionRecordCreateWithoutAssetInput!]
  }
  TransactionRecordCreateOrConnectWithoutAssetInput: { // input type
    create: NexusGenInputs['TransactionRecordCreateWithoutAssetInput']; // TransactionRecordCreateWithoutAssetInput!
    where: NexusGenInputs['TransactionRecordWhereUniqueInput']; // TransactionRecordWhereUniqueInput!
  }
  TransactionRecordCreateWithoutAssetInput: { // input type
    assetQuantity: number; // Int!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    currency: string; // String!
    date?: NexusGenScalars['DateTime'] | null; // DateTime
    note?: string | null; // String
    transactionType: NexusGenEnums['TransactionType']; // TransactionType!
    unitPrice: number; // Int!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  TransactionRecordScalarWhereInput: { // input type
    AND?: NexusGenInputs['TransactionRecordScalarWhereInput'][] | null; // [TransactionRecordScalarWhereInput!]
    NOT?: NexusGenInputs['TransactionRecordScalarWhereInput'][] | null; // [TransactionRecordScalarWhereInput!]
    OR?: NexusGenInputs['TransactionRecordScalarWhereInput'][] | null; // [TransactionRecordScalarWhereInput!]
    assetId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    assetQuantity?: NexusGenInputs['IntFilter'] | null; // IntFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    currency?: NexusGenInputs['StringFilter'] | null; // StringFilter
    date?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    note?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    transactionType?: NexusGenInputs['EnumTransactionTypeFilter'] | null; // EnumTransactionTypeFilter
    unitPrice?: NexusGenInputs['IntFilter'] | null; // IntFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  TransactionRecordUpdateManyMutationInput: { // input type
    assetQuantity?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    currency?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    date?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    note?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    transactionType?: NexusGenInputs['EnumTransactionTypeFieldUpdateOperationsInput'] | null; // EnumTransactionTypeFieldUpdateOperationsInput
    unitPrice?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  TransactionRecordUpdateManyWithWhereWithoutAssetInput: { // input type
    data: NexusGenInputs['TransactionRecordUpdateManyMutationInput']; // TransactionRecordUpdateManyMutationInput!
    where: NexusGenInputs['TransactionRecordScalarWhereInput']; // TransactionRecordScalarWhereInput!
  }
  TransactionRecordUpdateManyWithoutAssetInput: { // input type
    connect?: NexusGenInputs['TransactionRecordWhereUniqueInput'][] | null; // [TransactionRecordWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['TransactionRecordCreateOrConnectWithoutAssetInput'][] | null; // [TransactionRecordCreateOrConnectWithoutAssetInput!]
    create?: NexusGenInputs['TransactionRecordCreateWithoutAssetInput'][] | null; // [TransactionRecordCreateWithoutAssetInput!]
    delete?: NexusGenInputs['TransactionRecordWhereUniqueInput'][] | null; // [TransactionRecordWhereUniqueInput!]
    deleteMany?: NexusGenInputs['TransactionRecordScalarWhereInput'][] | null; // [TransactionRecordScalarWhereInput!]
    disconnect?: NexusGenInputs['TransactionRecordWhereUniqueInput'][] | null; // [TransactionRecordWhereUniqueInput!]
    set?: NexusGenInputs['TransactionRecordWhereUniqueInput'][] | null; // [TransactionRecordWhereUniqueInput!]
    update?: NexusGenInputs['TransactionRecordUpdateWithWhereUniqueWithoutAssetInput'][] | null; // [TransactionRecordUpdateWithWhereUniqueWithoutAssetInput!]
    updateMany?: NexusGenInputs['TransactionRecordUpdateManyWithWhereWithoutAssetInput'][] | null; // [TransactionRecordUpdateManyWithWhereWithoutAssetInput!]
    upsert?: NexusGenInputs['TransactionRecordUpsertWithWhereUniqueWithoutAssetInput'][] | null; // [TransactionRecordUpsertWithWhereUniqueWithoutAssetInput!]
  }
  TransactionRecordUpdateWithWhereUniqueWithoutAssetInput: { // input type
    data: NexusGenInputs['TransactionRecordUpdateWithoutAssetInput']; // TransactionRecordUpdateWithoutAssetInput!
    where: NexusGenInputs['TransactionRecordWhereUniqueInput']; // TransactionRecordWhereUniqueInput!
  }
  TransactionRecordUpdateWithoutAssetInput: { // input type
    assetQuantity?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    currency?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    date?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    note?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    transactionType?: NexusGenInputs['EnumTransactionTypeFieldUpdateOperationsInput'] | null; // EnumTransactionTypeFieldUpdateOperationsInput
    unitPrice?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  TransactionRecordUpsertWithWhereUniqueWithoutAssetInput: { // input type
    create: NexusGenInputs['TransactionRecordCreateWithoutAssetInput']; // TransactionRecordCreateWithoutAssetInput!
    update: NexusGenInputs['TransactionRecordUpdateWithoutAssetInput']; // TransactionRecordUpdateWithoutAssetInput!
    where: NexusGenInputs['TransactionRecordWhereUniqueInput']; // TransactionRecordWhereUniqueInput!
  }
  TransactionRecordWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  UserCreateInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    name: string; // String!
    password: string; // String!
    portfolios?: NexusGenInputs['PortfolioCreateNestedManyWithoutOwnerInput'] | null; // PortfolioCreateNestedManyWithoutOwnerInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserCreateNestedOneWithoutPortfoliosInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutPortfoliosInput'] | null; // UserCreateOrConnectWithoutPortfoliosInput
    create?: NexusGenInputs['UserCreateWithoutPortfoliosInput'] | null; // UserCreateWithoutPortfoliosInput
  }
  UserCreateOrConnectWithoutPortfoliosInput: { // input type
    create: NexusGenInputs['UserCreateWithoutPortfoliosInput']; // UserCreateWithoutPortfoliosInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserCreateWithoutPortfoliosInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    name: string; // String!
    password: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserUpdateInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    password?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    portfolios?: NexusGenInputs['PortfolioUpdateManyWithoutOwnerInput'] | null; // PortfolioUpdateManyWithoutOwnerInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  UserUpdateOneRequiredWithoutPortfoliosInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutPortfoliosInput'] | null; // UserCreateOrConnectWithoutPortfoliosInput
    create?: NexusGenInputs['UserCreateWithoutPortfoliosInput'] | null; // UserCreateWithoutPortfoliosInput
    update?: NexusGenInputs['UserUpdateWithoutPortfoliosInput'] | null; // UserUpdateWithoutPortfoliosInput
    upsert?: NexusGenInputs['UserUpsertWithoutPortfoliosInput'] | null; // UserUpsertWithoutPortfoliosInput
  }
  UserUpdateWithoutPortfoliosInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    password?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  UserUpsertWithoutPortfoliosInput: { // input type
    create: NexusGenInputs['UserCreateWithoutPortfoliosInput']; // UserCreateWithoutPortfoliosInput!
    update: NexusGenInputs['UserUpdateWithoutPortfoliosInput']; // UserUpdateWithoutPortfoliosInput!
  }
  UserWhereUniqueInput: { // input type
    email?: string | null; // String
    id?: number | null; // Int
  }
}

export interface NexusGenEnums {
  QueryMode: "default" | "insensitive"
  TransactionType: "buy" | "sell"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Asset: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description?: string | null; // String
    id: number; // Int!
    name: string; // String!
    portfolioId: number; // Int!
    quantity: number; // Int!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  AuthPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  HistoricalValue: { // root type
    assetId: number; // Int!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    date: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    unitPrice: number; // Int!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Mutation: {};
  Portfolio: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description?: string | null; // String
    id: number; // Int!
    name: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  PrivateAsset: { // root type
    id: number; // Int!
  }
  PublicAsset: { // root type
    id: number; // Int!
    market?: string | null; // String
    symbol?: string | null; // String
  }
  Query: {};
  Transaction: { // root type
    assetId: number; // Int!
    assetQuantity: number; // Int!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    currency: string; // String!
    date: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    note?: string | null; // String
    transactionType: NexusGenEnums['TransactionType']; // TransactionType!
    unitPrice: number; // Int!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  User: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    email: string; // String!
    id: number; // Int!
    name: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Asset: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string | null; // String
    id: number; // Int!
    name: string; // String!
    portfolioId: number; // Int!
    quantity: number; // Int!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  HistoricalValue: { // field return type
    assetId: number; // Int!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    date: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    unitPrice: number; // Int!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Mutation: { // field return type
    createOneHistoricalValue: NexusGenRootTypes['HistoricalValue']; // HistoricalValue!
    createOnePortfolio: NexusGenRootTypes['Portfolio']; // Portfolio!
    createOnePrivateAsset: NexusGenRootTypes['PrivateAsset']; // PrivateAsset!
    createOnePublicAsset: NexusGenRootTypes['PublicAsset']; // PublicAsset!
    createOneUser: NexusGenRootTypes['User']; // User!
    deleteOneHistoricalValue: NexusGenRootTypes['HistoricalValue'] | null; // HistoricalValue
    deleteOnePortfolio: NexusGenRootTypes['Portfolio'] | null; // Portfolio
    deleteOnePrivateAsset: NexusGenRootTypes['PrivateAsset'] | null; // PrivateAsset
    deleteOnePublicAsset: NexusGenRootTypes['PublicAsset'] | null; // PublicAsset
    deleteOneUser: NexusGenRootTypes['User'] | null; // User
    login: NexusGenRootTypes['AuthPayload'] | null; // AuthPayload
    makeTransaction: NexusGenRootTypes['Transaction']; // Transaction!
    updateOneHistoricalValue: NexusGenRootTypes['HistoricalValue'] | null; // HistoricalValue
    updateOnePortfolio: NexusGenRootTypes['Portfolio'] | null; // Portfolio
    updateOnePrivateAsset: NexusGenRootTypes['PrivateAsset'] | null; // PrivateAsset
    updateOnePublicAsset: NexusGenRootTypes['PublicAsset'] | null; // PublicAsset
    updateOneUser: NexusGenRootTypes['User'] | null; // User
  }
  Portfolio: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string | null; // String
    id: number; // Int!
    name: string; // String!
    owner: NexusGenRootTypes['User']; // User!
    privateAssets: Array<NexusGenRootTypes['PrivateAsset'] | null> | null; // [PrivateAsset]
    publicAssets: Array<NexusGenRootTypes['PublicAsset'] | null> | null; // [PublicAsset]
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  PrivateAsset: { // field return type
    baseAsset: NexusGenRootTypes['Asset']; // Asset!
    historicalValues: NexusGenRootTypes['HistoricalValue'][]; // [HistoricalValue!]!
    id: number; // Int!
  }
  PublicAsset: { // field return type
    baseAsset: NexusGenRootTypes['Asset']; // Asset!
    id: number; // Int!
    market: string | null; // String
    symbol: string | null; // String
  }
  Query: { // field return type
    myPortfolios: Array<NexusGenRootTypes['Portfolio'] | null> | null; // [Portfolio]
    myUser: NexusGenRootTypes['User'] | null; // User
    portfolio: NexusGenRootTypes['Portfolio'] | null; // Portfolio
    privateAsset: NexusGenRootTypes['PrivateAsset'] | null; // PrivateAsset
    privateAssets: NexusGenRootTypes['PrivateAsset'][]; // [PrivateAsset!]!
    publicAsset: NexusGenRootTypes['PublicAsset'] | null; // PublicAsset
    publicAssets: NexusGenRootTypes['PublicAsset'][]; // [PublicAsset!]!
  }
  Transaction: { // field return type
    assetId: number; // Int!
    assetQuantity: number; // Int!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    currency: string; // String!
    date: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    note: string | null; // String
    totalPrice: number; // Int!
    transactionType: NexusGenEnums['TransactionType']; // TransactionType!
    unitPrice: number; // Int!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  User: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    email: string; // String!
    id: number; // Int!
    name: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
}

export interface NexusGenFieldTypeNames {
  Asset: { // field return type name
    createdAt: 'DateTime'
    description: 'String'
    id: 'Int'
    name: 'String'
    portfolioId: 'Int'
    quantity: 'Int'
    updatedAt: 'DateTime'
  }
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  HistoricalValue: { // field return type name
    assetId: 'Int'
    createdAt: 'DateTime'
    date: 'DateTime'
    id: 'Int'
    unitPrice: 'Int'
    updatedAt: 'DateTime'
  }
  Mutation: { // field return type name
    createOneHistoricalValue: 'HistoricalValue'
    createOnePortfolio: 'Portfolio'
    createOnePrivateAsset: 'PrivateAsset'
    createOnePublicAsset: 'PublicAsset'
    createOneUser: 'User'
    deleteOneHistoricalValue: 'HistoricalValue'
    deleteOnePortfolio: 'Portfolio'
    deleteOnePrivateAsset: 'PrivateAsset'
    deleteOnePublicAsset: 'PublicAsset'
    deleteOneUser: 'User'
    login: 'AuthPayload'
    makeTransaction: 'Transaction'
    updateOneHistoricalValue: 'HistoricalValue'
    updateOnePortfolio: 'Portfolio'
    updateOnePrivateAsset: 'PrivateAsset'
    updateOnePublicAsset: 'PublicAsset'
    updateOneUser: 'User'
  }
  Portfolio: { // field return type name
    createdAt: 'DateTime'
    description: 'String'
    id: 'Int'
    name: 'String'
    owner: 'User'
    privateAssets: 'PrivateAsset'
    publicAssets: 'PublicAsset'
    updatedAt: 'DateTime'
  }
  PrivateAsset: { // field return type name
    baseAsset: 'Asset'
    historicalValues: 'HistoricalValue'
    id: 'Int'
  }
  PublicAsset: { // field return type name
    baseAsset: 'Asset'
    id: 'Int'
    market: 'String'
    symbol: 'String'
  }
  Query: { // field return type name
    myPortfolios: 'Portfolio'
    myUser: 'User'
    portfolio: 'Portfolio'
    privateAsset: 'PrivateAsset'
    privateAssets: 'PrivateAsset'
    publicAsset: 'PublicAsset'
    publicAssets: 'PublicAsset'
  }
  Transaction: { // field return type name
    assetId: 'Int'
    assetQuantity: 'Int'
    createdAt: 'DateTime'
    currency: 'String'
    date: 'DateTime'
    id: 'Int'
    note: 'String'
    totalPrice: 'Int'
    transactionType: 'TransactionType'
    unitPrice: 'Int'
    updatedAt: 'DateTime'
  }
  User: { // field return type name
    createdAt: 'DateTime'
    email: 'String'
    id: 'Int'
    name: 'String'
    updatedAt: 'DateTime'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOneHistoricalValue: { // args
      data: NexusGenInputs['HistoricalValueCreateInput']; // HistoricalValueCreateInput!
    }
    createOnePortfolio: { // args
      data: NexusGenInputs['PortfolioCreateInput']; // PortfolioCreateInput!
    }
    createOnePrivateAsset: { // args
      data: NexusGenInputs['PrivateAssetCreateInput']; // PrivateAssetCreateInput!
    }
    createOnePublicAsset: { // args
      data: NexusGenInputs['PublicAssetCreateInput']; // PublicAssetCreateInput!
    }
    createOneUser: { // args
      data: NexusGenInputs['UserCreateInput']; // UserCreateInput!
    }
    deleteOneHistoricalValue: { // args
      where: NexusGenInputs['HistoricalValueWhereUniqueInput']; // HistoricalValueWhereUniqueInput!
    }
    deleteOnePortfolio: { // args
      where: NexusGenInputs['PortfolioWhereUniqueInput']; // PortfolioWhereUniqueInput!
    }
    deleteOnePrivateAsset: { // args
      where: NexusGenInputs['PrivateAssetWhereUniqueInput']; // PrivateAssetWhereUniqueInput!
    }
    deleteOnePublicAsset: { // args
      where: NexusGenInputs['PublicAssetWhereUniqueInput']; // PublicAssetWhereUniqueInput!
    }
    deleteOneUser: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    makeTransaction: { // args
      data: NexusGenInputs['TransactionCreateInput']; // TransactionCreateInput!
    }
    updateOneHistoricalValue: { // args
      data: NexusGenInputs['HistoricalValueUpdateInput']; // HistoricalValueUpdateInput!
      where: NexusGenInputs['HistoricalValueWhereUniqueInput']; // HistoricalValueWhereUniqueInput!
    }
    updateOnePortfolio: { // args
      data: NexusGenInputs['PortfolioUpdateInput']; // PortfolioUpdateInput!
      where: NexusGenInputs['PortfolioWhereUniqueInput']; // PortfolioWhereUniqueInput!
    }
    updateOnePrivateAsset: { // args
      data: NexusGenInputs['PrivateAssetUpdateInput']; // PrivateAssetUpdateInput!
      where: NexusGenInputs['PrivateAssetWhereUniqueInput']; // PrivateAssetWhereUniqueInput!
    }
    updateOnePublicAsset: { // args
      data: NexusGenInputs['PublicAssetUpdateInput']; // PublicAssetUpdateInput!
      where: NexusGenInputs['PublicAssetWhereUniqueInput']; // PublicAssetWhereUniqueInput!
    }
    updateOneUser: { // args
      data: NexusGenInputs['UserUpdateInput']; // UserUpdateInput!
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
  }
  PrivateAsset: {
    historicalValues: { // args
      after?: NexusGenInputs['HistoricalValueWhereUniqueInput'] | null; // HistoricalValueWhereUniqueInput
      before?: NexusGenInputs['HistoricalValueWhereUniqueInput'] | null; // HistoricalValueWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Query: {
    portfolio: { // args
      where: NexusGenInputs['PortfolioWhereUniqueInput']; // PortfolioWhereUniqueInput!
    }
    privateAsset: { // args
      where: NexusGenInputs['PrivateAssetWhereUniqueInput']; // PrivateAssetWhereUniqueInput!
    }
    privateAssets: { // args
      after?: NexusGenInputs['PrivateAssetWhereUniqueInput'] | null; // PrivateAssetWhereUniqueInput
      before?: NexusGenInputs['PrivateAssetWhereUniqueInput'] | null; // PrivateAssetWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    publicAsset: { // args
      where: NexusGenInputs['PublicAssetWhereUniqueInput']; // PublicAssetWhereUniqueInput!
    }
    publicAssets: { // args
      after?: NexusGenInputs['PublicAssetWhereUniqueInput'] | null; // PublicAssetWhereUniqueInput
      before?: NexusGenInputs['PublicAssetWhereUniqueInput'] | null; // PublicAssetWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: ContextModule;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}